type: rpm-ostree
install:
# not sure why I need to add this
  - bolt

# desktop
  - dex-autostart
  
# launcher
  - rofi-wayland

# shell
  - fish

# editor
  - helix

# podman
  - podman-compose
  - podman-tui
  - podman-plugins
  - podmansh

# virtualization
  - libvirt
  - virt-manager
  - qemu-char-spice
  - qemu-device-display-virtio-gpu
  - qemu-device-display-virtio-vga
  - qemu-device-usb-redirect
  - qemu-img
  - qemu-system-x86-core
  - qemu-user-binfmt
  - qemu-user-static
  - qemu
